[public_private]
name = "Move to public or private"
command = "/bin/bash scripts/actions/public_private"
accepted_return_codes = [0]
description = "Change the public access of the app."

    [public_private.arguments]
        [public_private.arguments.is_public]
            type = "boolean"
            ask = "Is it a public app ?"
            default = true

[disable_maintenance]
name = "Disable the maintenance mode of Wordpress"
command = "/bin/bash scripts/actions/disable_maintenance"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Disable the maintenance mode of Wordpress if you're stuck after an upgrade"
