packaging_format = 2

id = "wordpress"
name = "WordPress"
description.en = "Create a beautiful blog or website easily"
description.fr = "Logiciel de création de blog ou de site Web"

version = "6.2~ynh1"

maintainers = ["kay0u"]

[upstream]
license = "GPL-2.0"
website = "https://wordpress.org/"
admindoc = "https://codex.wordpress.org/"
code = "https://core.trac.wordpress.org/browser"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.1.18"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/blog"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["en_US", "fr_FR"]
    default = "en_US"

    [install.admin]
    type = "user"

    [install.multisite]
    ask.en = "Enable multisite option?"
    ask.fr = "Activer l'option multisite ?"
    type = "boolean"
    default = false

[resources]
        [resources.sources.main]
        url = "https://downloads.wordpress.org/release/wordpress-6.2.zip"
        sha256 = "0078e0483d3447a465f71d6bbdab5c799cad2e57c221ec1d639d235b0ffced55"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.url = "/wp-login.php"
    admin.additional_urls="/wp-admin.php"
    admin.allowed = "admins"

    [resources.apt]
    packages = "mariadb-server php8.0-mysql php8.0-curl php8.0-json php8.0-mbstring php8.0-xml php8.0-zip php8.0-gd php8.0-soap php8.0-ssh2 php8.0-tokenizer php8.0-ldap"

    [resources.database]
    type = "mysql"
